select * 
from information_schema.tables -- explore all object in the db
WHERE table_schema = 'bronze';
select * 
-- ---------------------------- -- 
from information_schema.columns 
WHERE table_schema = 'bronze'; -- explore all columns in the db
-- ---------------------------- -- 
 select  distinct(country)  -- explore all countries our customers come from
 from gold.dim_customers;
 -- ---------------------------- -- 
  select distinct category,subcategory,product_name -- explore all categories
  from gld.dim_product
  order by 1,2,3;
  -- ---------------------------- -- 
  select   min(order_date),max(order_date) ,(timestampdiff(month,min(order_date),max(order_date))) as month_difference,
  (timestampdiff(year,min(order_date),max(order_date))) as year_difference
  from gold.fact_Sales; -- exploring order_dates
  -- ------------------------------------------------------------ --
  select timestampdiff(year,min(birth_Date),current_date()),timestampdiff(year,max(birth_Date),current_date())
  from
  gold.dim_customers ; -- exploring age  range 
  -- ----------------------------------------------------------------- --
  select sum(sls_sales) as total_sales,sum(sls_quantity) as total_quantity, avg(sls_price),
  count(distinct order_number) as total_orders , count( distinct(customer_key) ) as total_Customers ,
  count( distinct prdouct__key) as total_prducts
  from gold.fact_Sales; -- measures exploration 
  -- ------------------------------------------------- -- 
  select country, count(customer_key) as total_customers
 from  gold.dim_customers
 group by country
 order by 2 desc ; -- total customers by country 
  --  ------------------------------------------------- --
   select gender, count(customer_key) as total_customers
 from  gold.dim_customers
 group by gender
 order by 2 desc ; -- total customers by gender 
 -- --------------------------------  --
 select category_name, count(prdouct__key) as total_products
 from gold.dim_product
 group by category_name
 order by 2 desc ;  -- total products by category 
  -- ----------------------------------------------- --
   Select category_name, round(avg(product_cost),0) as avg_prdouct_cost_per_category
 from gold.dim_product
 group by category_name
 order by 2 desc ;  -- avg_prdouct_cost_per_category
 -- ------------------------------------------------------------- -- 
  select d.category_name as category_name, sum(s.sls_sales) as total_revenue 
  from gold.fact_Sales s
left join gold.dim_product d
on s.prdouct__key = d.prdouct__key
group by 1
order by 2 desc; -- total revenue by each product 
 -- ------------------------------------------------------------------ --
 select  c.customer_key, c.first_name,c.last_name, sum(s.sls_sales) as total_revenue
 from  gold.fact_Sales s
 left join gold.dim_customers c
 on s.customer_key= c.customer_key
 group by 1,2,3
 order by 4  desc;   -- total revenue generated by each customer 
-- ----------------------------------------------------------- -- 
 select  c.country,  sum(sls_quantity) as total_quantities
 from  gold.fact_Sales s
 left join gold.dim_customers c
 on s.customer_key= c.customer_key
 group by 1
 order by 2  desc;  -- the distribution of sold items across countries 
 -- ----------------------------------------------------------------- --
 select d.product_name as product_name, sum(s.sls_sales) as total_revenue ,
  dense_rank() over( order by sum(s.sls_sales) desc ) as top_product
  from gold.fact_Sales s
left join gold.dim_product d
on s.prdouct__key = d.prdouct__key
group by 1
 --  top_product by total revenue 
limit 5 ;
-- -------------------------------------------------------------------- --
select d.product_name as category_name, sum(s.sls_sales) as total_revenue ,
  dense_rank() over( order by sum(s.sls_sales) asc ) as Bottom_products
  from gold.fact_Sales s
left join gold.dim_product d
on s.prdouct__key = d.prdouct__key
group by 1
 --  worst _product by total revenue 
limit 5 ;
-- --------------- ---------------------------------------------------- -- 
select  c.customer_key, c.first_name,c.last_name, count( distinct s.order_number) as total_orders
 from  gold.fact_Sales s
 left join gold.dim_customers c
 on s.customer_key= c.customer_key
 group by 1,2,3
 order by 4  asc 
 limit  3 -- customers with the fewest order palced 